In [1]:
import torch

In [3]:
#Gradient of function wrt x

x = torch.randn((1,5), requires_grad=True)
x

tensor([[ 0.2953,  0.3657,  0.5039, -0.2975,  0.8954]], requires_grad=True)

In [4]:
b = x + 2
b

tensor([[2.2953, 2.3657, 2.5039, 1.7025, 2.8954]], grad_fn=<AddBackward0>)

In [5]:
#Add another operation
c = b * 2
c

tensor([[4.5905, 4.7314, 5.0078, 3.4051, 5.7909]], grad_fn=<MulBackward0>)

In [6]:
c = c.mean()
c

tensor(4.7051, grad_fn=<MeanBackward0>)

In [7]:
#How can we get the gradients for x
x.grad

In [8]:
#To see backward propragation
c.backward()

In [10]:
x.grad

tensor([[0.4000, 0.4000, 0.4000, 0.4000, 0.4000]])