In [1]:
import torch

In [2]:
input_img = torch.randn((1,10))

In [3]:
input_img

tensor([[-0.0203,  1.4406, -0.7684,  0.8722,  2.3672,  0.2330,  0.3729, -2.2245,
         -1.0307, -0.2632]])

In [4]:
#Same shape
weights = torch.randn_like(input_img)

In [5]:
weights

tensor([[-0.1980,  0.0167, -0.4217,  0.3833, -0.0816,  0.6743,  0.9723,  1.4722,
          1.1064, -0.1417]])

In [6]:
bias = torch.randn((1,1))

In [7]:
bias

tensor([[-0.4938]])

In [8]:
#y(predicted) = x1.w1 + x2.w2 + ...... + xn.wn
input_img * weights

tensor([[ 0.0040,  0.0241,  0.3240,  0.3343, -0.1931,  0.1571,  0.3626, -3.2750,
         -1.1404,  0.0373]])

In [10]:
#gives error
output = torch.mm(input_img, weights.view(10,1)) + bias

In [11]:
output

tensor([[-3.8589]])

In [13]:
#Using activation function
#To squeeze the output between 0 and 1 (or some probability)
#Here, using sigmoid function

def sigmoid(x):
    return 1/(1+torch.exp(-x))

In [15]:
output = sigmoid(output)

In [16]:
output

tensor([[0.0173]])

In [ ]:
#Matrix multiplication functions

#mm - does matrix multiplication but does not support broadcasting

#matmul - supports multiplication but also performs different applications based
#on the shape and dimension, also supports broadcasting

#To perform reshaping

#reshape - returns a tensor with the same data and a number of elements of elements 
#as input but with a specific shape

#resize_ - will anyplace operation, which at least had some elements without showing
#that error 

#view - show an error in case you are using some elements