In [ ]:
import torch


In [ ]:
x = torch.Tensor([1,2,3])

In [ ]:
x

tensor([1., 2., 3.])

In [ ]:
x[2]

tensor(3.)

In [ ]:
x.shape

torch.Size([3])

In [ ]:
x + torch.Tensor([4,4,4])

tensor([5., 6., 7.])

In [ ]:
#Broadcasting
x + 5

tensor([6., 7., 8.])

In [ ]:
x = torch.Tensor([[1,2,3],[4,5,6]])

In [ ]:
x

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [ ]:
x[0,1]

tensor(2.)

In [ ]:
#Multidimensional broadcasting
x + 5

tensor([[ 6.,  7.,  8.],
        [ 9., 10., 11.]])

In [ ]:
#Generate a random Tensor
x = torch.randn((1,5))

In [ ]:
x

tensor([[-0.4825,  0.6575, -0.3138,  0.5319,  0.1159]])

In [ ]:
x = torch.randn((2,3))

In [ ]:
x

tensor([[ 0.9733,  1.5859, -0.6813],
        [-0.9845,  0.9480, -1.1326]])