In [1]:
import torch

In [2]:
input_img = torch.randn((1,10))

In [3]:
input_img

tensor([[-0.0629, -1.0568,  1.7145,  0.4780, -0.1133, -0.6213, -0.8921,  0.5324,
         -1.5198, -1.4230]])

In [4]:
#Same shape
weights = torch.randn_like(input_img)

In [5]:
weights

tensor([[ 0.4418, -1.0223, -0.3774,  0.4638, -0.1308,  0.2595,  1.6812, -0.3723,
         -0.0051,  1.1149]])

In [6]:
bias = torch.randn((1,1))

In [7]:
bias

tensor([[-1.2459]])

In [8]:
#y(predicted) = x1.w1 + x2.w2 + ...... + xn.wn
input_img * weights

tensor([[-0.0278,  1.0803, -0.6471,  0.2217,  0.0148, -0.1612, -1.4997, -0.1982,
          0.0077, -1.5865]])

In [11]:
output = torch.sum(input_img * weights) + bias
#or can do (input_img * weights).sum

In [12]:
output

tensor([[-4.0420]])

In [13]:
#Using activation function
#To squeeze the output between 0 and 1 (or some probability)
#Here, using sigmoid function

def sigmoid(x):
    return 1/(1+torch.exp(-x))

In [15]:
output = sigmoid(output)

In [16]:
output

tensor([[0.0173]])